name: Logistics
configs:
  Release: release
  Debug: debug
attributes:
  ORGANIZATIONNAME: HyperTrack
options:
  minimumXcodeGenVersion: 2.3.0
  deploymentTarget:
    iOS: 13.0
  defaultConfig: Release
  groupSortPosition: top
  developmentLanguage: en
schemes:
  Logistics:
    build:
      targets:
        Logistics: all
settings:
  base:
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: 1
    SWIFT_ENABLE_BATCH_MODE: NO
  configs:
    Release:
      ENABLE_TESTABILITY: NO
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      VALIDATE_PRODUCT: YES
    Debug:
      ENABLE_TESTABILITY: YES
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      VALIDATE_PRODUCT: NO
targetTemplates:
  Framework:
    platform: iOS
    deploymentTarget: 13.0
    type: framework
    sources:
      - path: ${target_name}
        excludes:
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ""
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        CLANG_ENABLE_OBJC_WEAK: YES
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        DEFINES_MODULE: YES
        DEVELOPMENT_TEAM: H4925W78YQ
        ENABLE_BITCODE: NO
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)
        INFOPLIST_FILE: $(SRCROOT)/${target_name}/Info.plist
        LD_RUNPATH_SEARCH_PATHS: $(inherited)
        MARKETING_VERSION: "1.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.hypertrack.logistics.${target_name}
        PRODUCT_NAME: $(TARGET_NAME:c99extidentifier)
        SKIP_INSTALL: YES
        TARGETED_DEVICE_FAMILY: 1
        XCODEGEN_STATE: YES
  FrameworkLogic:
    templates:
      - Framework
      - Dep1
      - Dep2
    templateAttributes:
      dep1: ComposableArchitecture
      dep2: Prelude
  FrameworkView:
    templates:
      - Framework
      - Dep1
      - Dep2
      - Dep3
    templateAttributes:
      dep1: ComposableArchitecture
      dep2: Prelude
      dep3: ViewsComponents
  Test:
    type: bundle.unit-test
    platform: iOS
    sources: ${target_name}
    dependencies:
      - target: ${depT}
  Dep1:
    dependencies:
      - target: ${dep1}
      - sdk: ${dep1}.framework
        embed: false
  Dep2:
    dependencies:
      - target: ${dep2}
      - sdk: ${dep2}.framework
        embed: false
  Dep3:
    dependencies:
      - target: ${dep3}
      - sdk: ${dep3}.framework
        embed: false
  Dep4:
    dependencies:
      - target: ${dep4}
      - sdk: ${dep4}.framework
        embed: false
  Dep5:
    dependencies:
      - target: ${dep5}
      - sdk: ${dep5}.framework
        embed: false
targets:
  App:
    templates:
      - Framework
    dependencies:
      - target: ComposableArchitecture
      - sdk: ComposableArchitecture.framework
      - target: Deeplink
      - sdk: Deeplink.framework
      - target: Deliveries
      - sdk: Deliveries.framework
      - target: Delivery
      - sdk: Delivery.framework
      - target: DriverID
      - sdk: DriverID.framework
      - target: Prelude
      - sdk: Prelude.framework
      - target: Location
      - sdk: Location.framework
      - target: Motion
      - sdk: Motion.framework
      - target: Notification
      - sdk: Notification.framework
      - target: Reachability
      - sdk: Reachability.framework
      - target: Restoration
      - sdk: Restoration.framework
      - target: SignIn
      - sdk: SignIn.framework
      - target: Tracking
      - sdk: Tracking.framework
      - target: ViewBlocker
      - sdk: ViewBlocker.framework
      - target: ViewsComponents
      - sdk: ViewsComponents.framework
  AppTests:
    templates:
      - Test
    templateAttributes:
      depT: App
  ComposableArchitecture:
    templates:
      - Framework
      - Dep1
    templateAttributes:
      dep1: Prelude
  Deeplink:
    templates:
      - FrameworkLogic
  DeeplinkLive:
    templates:
      - FrameworkLogic
      - Dep3
    templateAttributes:
      dep3: Deeplink
  DeeplinkTests:
    templates:
      - Test
    templateAttributes:
      depT: Deeplink
  Deliveries:
    templates:
      - FrameworkView
  DeliveriesTests:
    templates:
      - Test
    templateAttributes:
      depT: Deliveries
  Delivery:
    templates:
      - FrameworkView
  DeliveryTests:
    templates:
      - Test
    templateAttributes:
      depT: Delivery
  DriverID:
    templates:
      - FrameworkView
  DriverIDTests:
    templates:
      - Test
    templateAttributes:
      depT: DriverID
  Location:
    templates:
      - FrameworkLogic
  LocationTests:
    templates:
      - Test
    templateAttributes:
      depT: Location
  LocationLive:
    templates:
      - FrameworkLogic
      - Dep3
    templateAttributes:
      dep3: Location
  Logistics:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    dependencies:
      - target: App
      - sdk: App.framework
      - target: ComposableArchitecture
      - sdk: ComposableArchitecture.framework
      - target: Deeplink
      - sdk: Deeplink.framework
      - target: DeeplinkLive
      - sdk: DeeplinkLive.framework
      - target: Deliveries
      - sdk: Deliveries.framework
      - target: Delivery
      - sdk: Delivery.framework
      - target: DriverID
      - sdk: DriverID.framework
      - target: Prelude
      - sdk: Prelude.framework
      - target: Location
      - sdk: Location.framework
      - target: LocationLive
      - sdk: LocationLive.framework
      - target: Motion
      - sdk: Motion.framework
      - target: MotionLive
      - sdk: MotionLive.framework
      - target: Notification
      - sdk: Notification.framework
      - target: NotificationLive
      - sdk: NotificationLive.framework
      - target: Reachability
      - sdk: Reachability.framework
      - target: ReachabilityLive
      - sdk: ReachabilityLive.framework
      - target: Restoration
      - sdk: Restoration.framework
      - target: RestorationLive
      - sdk: RestorationLive.framework
      - target: SignIn
      - sdk: SignIn.framework
      - target: Tracking
      - sdk: Tracking.framework
      - target: TrackingLive
      - sdk: TrackingLive.framework
      - target: ViewBlocker
      - sdk: ViewBlocker.framework
      - target: ViewsComponents
      - sdk: ViewsComponents.framework
    sources:
      - Logistics
    settings:
      base:
        CLANG_ENABLE_OBJC_WEAK: YES
        CODE_SIGN_ENTITLEMENTS: $(TARGET_NAME)/$(TARGET_NAME).entitlements
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 10
        DEVELOPMENT_TEAM: H4925W78YQ
        ENABLE_BITCODE: NO
        INFOPLIST_FILE: $(SRCROOT)/Logistics/Info.plist
        LD_RUNPATH_SEARCH_PATHS: $(inherited)
        MARKETING_VERSION: "1.0.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.hypertrack.logistics.ios.store
        PRODUCT_MODULE_NAME: $(TARGET_NAME)
        PRODUCT_NAME: $(TARGET_NAME)
        TARGETED_DEVICE_FAMILY: 1
        VERSIONING_SYSTEM: apple-generic
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG HYPERTRACK
  Motion:
    templates:
      - FrameworkLogic
  MotionTests:
    templates:
      - Test
    templateAttributes:
      depT: Motion
  MotionLive:
    templates:
      - FrameworkLogic
      - Dep3
    templateAttributes:
      dep3: Motion
  Notification:
    templates:
      - FrameworkLogic
  NotificationTests:
    templates:
      - Test
    templateAttributes:
      depT: Notification
  NotificationLive:
    templates:
      - FrameworkLogic
      - Dep3
    templateAttributes:
      dep3: Notification
  Prelude:
    templates:
      - Framework
  Reachability:
    templates:
      - FrameworkLogic
  ReachabilityLive:
    templates:
      - FrameworkLogic
      - Dep3
    templateAttributes:
      dep3: Reachability
  ReachabilityTests:
    templates:
      - Test
    templateAttributes:
      depT: Reachability
  Restoration:
    templates:
      - FrameworkLogic
  RestorationLive:
    templates:
      - FrameworkLogic
      - Dep3
    templateAttributes:
      dep3: Restoration
  RestorationTests:
    templates:
      - Test
    templateAttributes:
      depT: Restoration
  SignIn:
    templates:
      - FrameworkView
  SignInTests:
    templates:
      - Test
    templateAttributes:
      depT: SignIn
  Tracking:
    templates:
      - FrameworkLogic
  TrackingLive:
    templates:
      - FrameworkLogic
  TrackingTests:
    templates:
      - Test
    templateAttributes:
      depT: Tracking
  ViewBlocker:
    templates:
      - FrameworkView
  ViewsComponents:
    templates:
      - Framework
      - Dep1
    templateAttributes:
      dep1: Prelude
